/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f0f5ee",
        "surface-container": "#eaefe8",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-secondary-container": "#626566",
        "on-secondary-fixed-variant": "#454748",
        "surface-tint": "#006d41",
        "primary-fixed": "#8ef8b8",
        "outline-variant": "#bdcabe",
        "on-secondary": "#ffffff",
        "tertiary-container": "#ba545f",
        "on-secondary-fixed": "#191c1d",
        "secondary-fixed": "#e1e3e4",
        "tertiary-fixed-dim": "#ffb2b7",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#edf2eb",
        "primary-fixed-dim": "#72db9e",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        "tertiary-fixed": "#ffdadb",
        "primary-container": "#058651",
        "secondary-container": "#e1e3e4",
        "surface-dim": "#d6dcd4",
        tertiary: "#9b3c47",
        "on-tertiary-fixed-variant": "#7f2833",
        "on-primary-container": "#f6fff5",
        "on-error": "#ffffff",
        "on-background": "#171d19",
        surface: "#f5fbf3",
        primary: "#006a3f",
        "secondary-fixed-dim": "#c5c7c8",
        "inverse-surface": "#2c322d",
        secondary: "#5c5f60",
        "on-primary-fixed": "#002110",
        "on-surface-variant": "#3e4941",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e4eae2",
        "surface-container-highest": "#dee4dd",
        "on-tertiary-fixed": "#40000d",
        "surface-variant": "#dee4dd",
        "on-primary-fixed-variant": "#00522f",
        "surface-on-surface": "#171d19",
        "on-surface": "#171d19",
        outline: "#6e7a70",
        "inverse-primary": "#72db9e",
        "surface-bright": "#f5fbf3",
        background: "#f5fbf3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      keyframes: {
        "exercise-hero-in": {
          "0%": { opacity: "0", transform: "scale(1.03)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "exercise-sheet-in": {
          "0%": { opacity: "0", transform: "translateY(14px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "exercise-row-in": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "exercise-hero-in":
          "exercise-hero-in 0.68s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "exercise-sheet-in":
          "exercise-sheet-in 0.72s cubic-bezier(0.16, 1, 0.3, 1) 0.05s forwards",
        "exercise-row-in":
          "exercise-row-in 0.5s cubic-bezier(0.16, 1, 0.3, 1) both",
      },
    },
  },
  plugins: [],
};
